<%= "package_assets: off" if ENV['RAILS_ENV'] == 'cucumber' || ENV['RAILS_ENV'] == 'test' %>
compress_assets: on
embed_assets: datauri

javascripts:
  common:
    - public/javascripts/jquery/jquery-1.4.2.min.js
    - public/javascripts/jquery/jquery.form.js
    - public/javascripts/jquery/jquery.nano.js
    - public/javascripts/jquery/effects.core.js
    - public/javascripts/jquery/effects.highlight.js
    - public/javascripts/application.js
  home:
    - public/javascripts/pages/home.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/taf-kickoff-large.css
    - public/stylesheets/layout.css
  home:
    - public/stylesheets/home.css

templates:
